# Config file used by Multi Labeller https://github.com/marketplace/actions/multi-labeler

version: v1

labels:
  - label: "macos"
    matcher:
      title: "mac"
  - label: "aix"
    matcher:
      title: "aix"
  - label: "windows"
    matcher:
      title: "windows"
  - label: "solaris"
    matcher:
      title: "solaris"
  - label: "linux"
    matcher:
      title: "linux"

  - label: "arm"
    matcher:
      title: "arm"
  - label: "aarch64"
    matcher:
      title: "aarch64"
  - label: "ppc64le"
    matcher:
      title: "ppc64le"
  - label: "s390x"
    matcher:
      title: "s390x"
  - label: "x64"
    matcher:
      title: "x64"
  - label: "sparcv9"
    matcher:
      title: "sparc"
  - label: "riscv"
    matcher:
      title: "riscv"

  - label: "hotspot"
    matcher:
      title: "hotspot"
  - label: "openj9"
    matcher:
      title: "openj9"
  - label: "dragonwell/alibaba"
    matcher:
      title: "dragonwell"
  - label: "bisheng"
    matcher:
      title: "bisheng"

  - label: "docker"
    matcher:
      title: "docker"
  - label: "hacktoberfest"
    matcher:
      body: "hacktoberfest"
  - label: "generation"
    matcher:
      title: "generat"